id: AFAF85475
title: 'The Bestowal of Supreme Blessings: Praise to the Vajradhara Loter Wangpo'
type: translation
pechas:
- IBE4A4B64
- I5A295066
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:38:27.490027
  last_modified_at: 2023-01-04 12:38:27.490031
  collections:
  - Jamyang Loter Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IBE4A4B64/460A: F55E
  I5A295066/374B: F55E
